<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "question".
 *
 * @property integer $id
 * @property string $user_id
 * @property integer $answer_id
 * @property string $body
 * @property string $created_at
 * @property string $updated_at
 */
class Question extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'question';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'answer_id', 'body'], 'required'],
            [['answer_id', 'user_id'], 'integer'],
            [['body'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'answer_id' => 'Answer ID',
            'body' => 'Ответ',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function beforeValidate()
    {
        $this->user_id = Yii::$app->user->getId();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function getUser(){
        return $this->hasOne(User::className(), ['id'=> 'user_id']);
    }

    public function getAnswer(){
        return $this->hasOne(User::className(), ['id'=> 'answer_id']);
    }
}
